---
title: "Code and Plots"
output:
  pdf_document: default
  pdf: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forecast)
library(tidyverse)
library(lubridate)
setwd("C:\\Users\\jloo1\\Dropbox\\Projects\\Retail-Demand-Prediction")
```

#Initial Exploration

```{r}
df <- read_csv("online_retail_II.csv")
head(df)
```

```{r}
df$InvoiceDate <- as_datetime(df$InvoiceDate)
df$year <- year(df$InvoiceDate)
df$month <- month(df$InvoiceDate)
df$week <- (isoweek(df$InvoiceDate))
df$day <- day(df$InvoiceDate)
df$weekday <- weekdays(df$InvoiceDate)
head(df)
```

```{r}
#Checking for data errors
sapply(df,function(x) sum(is.na(x)))
desc_na = df[is.na(df$Description),]
cust_na = df[is.na(df$`Customer ID`),]
df <- df[!is.na(df$Description),]
sapply(df,function(x) sum(is.na(x)))
cust_na = df[is.na(df$`Customer ID`),]
```


```{r}
#Getting daily, weekly, monthly sales data
df_sales_volumes_day <- df %>% group_by(year,month,day) %>% summarise(volume = sum(Quantity)) %>% ungroup()
df_sales_volumes_day$date <- as_date(with(df_sales_volumes_day,paste(year,month,day,sep="-")))
df_sales_volumes_day$ydays <- yday(df_sales_volumes_day$date)
df_sales_volumes_week <- df %>% group_by(year,week) %>% summarise(volume = sum(Quantity)) %>% ungroup()
df_sales_volumes_month <- df %>% group_by(year,month) %>% summarise(volume = sum(Quantity)) %>% ungroup()
```

```{r}
#Plotting daily, weekly, monthly sales data
sales_day <- ggplot(data = df_sales_volumes_day, aes(x=ydays,y=volume,group = year, colour=as.factor(year)))+geom_line()+theme(axis.text.x=element_text(angle=90))+
  labs(title = "Daily Total Sales Volume", x = "Day of the Year", y = "Total Sales Volume (Units)",colour = "Year")
sales_week <- ggplot(data = df_sales_volumes_week, aes(x=week,y=volume,group = year, colour=as.factor(year)))+
  geom_line()+geom_point()+theme(axis.text.x=element_text(angle=90))+
  labs(title = "Weekly Total Sales Volume", x = "Week of the Year", y = "Total Sales Volume (Units)",colour = "Year")
sales_month <- ggplot(data = df_sales_volumes_month, aes(x=month,y=volume,group = year, colour=as.factor(year)))+
  geom_line()+geom_point()+theme(axis.text.x=element_text(angle=90))+
  labs(title = "Monthly Total Sales Volume", x = "Month of the Year", y = "Total Sales Volume (Units)",colour = "Year")+
  scale_x_continuous(breaks=c(1:12))

sales_day
sales_week
sales_month
```

```{r}
#Getting last month's data grouped by customers and products
last_month = df[df$year==2011&df$month==11,]
last_month$StockCode = as.factor(last_month$StockCode)
last_month_product <- last_month %>% group_by(Description) %>% summarise(revenue = sum(Quantity*Price)) %>% ungroup()
last_month_customer <- last_month %>% group_by(`Customer ID`) %>% summarise(revenue = sum(Quantity*Price)) %>% ungroup()
last_month_customer <- last_month_customer %>% rename(`ID`="Customer ID",revenue="revenue")
last_month_customer$ID = as.character(last_month_customer$ID)
```

```{r}
#Plotting last month's product data
last_month_product <- last_month_product[order(-last_month_product$revenue),]
lmptop <- ggplot(data=last_month_product[c(1:5),], aes(x=reorder(Description,revenue), y=revenue, fill=reorder(Description,revenue)))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Top 5 Products by Revenue",ylab="Revenue",fill="Description")
lmptop2 <- ggplot(data=last_month_product[c(2:31),], aes(x=reorder(Description,revenue), y=revenue, fill=reorder(Description,revenue)))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Top 30 Products (ignoring postage)",ylab="Revenue",fill="Description")
lmptop
lmptop2

last_month_product <- last_month_product[order(last_month_product$revenue),]
lmpbot <- ggplot(data=last_month_product[c(1:5),], aes(x=reorder(Description,revenue), y=revenue, fill=reorder(Description,revenue)))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Bottom 5 Products by Revenue",ylab="Revenue",fill="Description")
lmpbot2 <- ggplot(data=last_month_product[c(6:35),], aes(x=reorder(Description,revenue), y=revenue, fill=reorder(Description,revenue)))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Bottom 30 Products by Revenue (ignoring payments and discounts)",ylab="Revenue",fill="Description")
lmpbot3 <- ggplot(data=last_month_product[c(55:84),], aes(x=reorder(Description,revenue), y=revenue, fill=reorder(Description,revenue)))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Bottom 30 Products with Positive Revenues",ylab="Revenue",fill="Description")
lmpbot
lmpbot2
lmpbot3
```

```{r}
#Plotting last month's customer data
last_month_customer <- last_month_customer[order(-last_month_customer$revenue),]
lmctop <- ggplot(data=last_month_customer[c(1:5),], aes(x=reorder(ID,revenue), y=revenue, fill=ID))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Top 5 Customers by Revenue",ylab="Revenue")
lmctop2 <- ggplot(data=last_month_customer[c(3:30),], aes(x=reorder(ID,revenue), y=revenue, fill=ID))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Top 30 Customers by Revenue (ignoring unknowns)",ylab="Revenue")
lmctop
lmctop2

last_month_customer <- last_month_customer[order(last_month_customer$revenue),]
lmcbot <- ggplot(data=last_month_customer[c(1:35),], aes(x=reorder(ID,revenue), y=revenue, fill=ID))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Bottom 30 Customers by Revenue",ylab="Revenue")
lmcbot2 <- ggplot(data=last_month_customer[c(51:80),], aes(x=reorder(ID,revenue), y=revenue, fill=ID))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Bottom 30 Customers by Revenue (ignoring negatives)",ylab="Revenue")
lmcbot
lmcbot2
```

```{r}
#Considering consumer country spread
lmcoun = last_month %>% group_by(Country) %>% summarise(revenue = sum(Quantity*Price)) %>% ungroup()
lmcount <- ggplot(data=lmcoun, aes(x=reorder(Country,revenue), y=revenue, fill=reorder(Country,revenue)))+geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(title="Countries by Revenue",ylab="Revenue")
lmcount
```


```{r}
#Finding the volume weighted average monthly sale price and plotting
vwap = df %>% group_by(year,month) %>% summarise(vwap = sum(Quantity*Price)/sum(Quantity)) %>% ungroup()
vwap_month <- ggplot(data = vwap, aes(x=month,y=vwap,group = year, colour=as.factor(year)))+
  geom_line()+geom_point()+theme(axis.text.x=element_text(angle=90))+
  labs(title = "Volume Weight Average Monthly Sale Price", x = "Month of the Year", y = "Total Sales Volume (Units)",colour = "Year")+
  scale_x_continuous(breaks=c(1:12))
vwap_month
```

```{r}
#Investing negative quantities, returns and how to account for cancellations for orders before the data collection period
df_neg = df[df$Quantity<0,]
neg_Cancellation = df[grepl('C',df$Invoice),]
non_na = df[!is.na(df$`Customer ID`),]
test = non_na[non_na$`Customer ID`==14590,]
test = non_na[non_na$`Customer ID`==12510,]
likely_precollection = df[grepl('C',df$Invoice)&df$year<2010,]
likely_precollection = likely_precollection[!is.na(likely_precollection$`Customer ID`),]
dates = likely_precollection$InvoiceDate
ID = likely_precollection$`Customer ID`
cID = likely_precollection$Invoice
before = numeric()
for (i in 1:nrow(likely_precollection)){
  if(sum((non_na$InvoiceDate<dates[i]&non_na$`Customer ID`==ID[i]))==0){
    before[length(before)+1] = cID[i]
  }
}
before = unique(before)
df = df[!df$Invoice%in%before,]
other_na = c("C489859","C489860","C489881","C490307")
df = df[!df$Invoice%in%other_na,]
```

```{r}
#Getting weekly revenue and plotting time-series data
weekly_sales = df %>% group_by(year,week) %>% summarise(Revenue=log(sum(Quantity*Price))) %>% ungroup()
weekly_sales$Date = as.character.Date(with(weekly_sales,paste(year,week,sep="-")))
sales <- ts(weekly_sales$Revenue,start = c(2009, 49),frequency = 52)
ggtsdisplay(sales,lag.max=60)
```

```{r}
#Getting monthly revenue and plotting time-series data
df = df[c(1:1037028),]
monthly_sales = df %>% group_by(year,month) %>% summarise(Revenue=log(sum(Quantity*Price))) %>% ungroup()
monthly_sales$Date = as.character.Date(with(monthly_sales,paste(year,month,sep="-")))
salesm <- ts(monthly_sales$Revenue,start = c(2009, 12),frequency = 12)
ggtsdisplay(salesm,lag.max=24)
```

```{r}
#Getting mle fitted models for weekly sales and checking for best AIC value
model = auto.arima(sales,approximation=FALSE,seasonal=FALSE)
model
model2 = arima(sales,order=c(5,0,0),seasonal=c(0,0,1))
model2
checkresiduals(model)
checkresiduals(model2)
```

```{r}
#Getting mle fitted models for monthly sales and checking a HoltWinters for comparison
modelm1 = auto.arima(salesm,stepwise=FALSE,parallel=TRUE)
modelm1
modelm2 = HoltWinters(salesm)
checkresiduals(modelm1)
modelm3 = arima(salesm, order=c(1,0,0),seasonal=c(0,0,1))
modelm3
checkresiduals(modelm3)
```

```{r}
#Forecasting with the fitted monthly time-series models
modelm1 %>% forecast(h=6) %>% autoplot() + ylab("Revenue (British Pounds") + xlab("Time")
modelm2 %>% forecast(h=6) %>% autoplot() + ylab("Revenue (British Pounds") + xlab("Time")
modelm3 %>% forecast(h=6) %>% autoplot() + ylab("Revenue (British Pounds") + xlab("Time")
```


```{r}
#Forecasting with the fitted weekly time-series models
model %>% forecast(h=24) %>% autoplot() + ylab("Revenue (British Pounds") + xlab("Time")
model2 %>% forecast(h=24) %>% autoplot() + ylab("Revenue (British Pounds") + xlab("Time")
```